"""
Apply a trained Random Forest model to all calibrated MAT images.

For each input MAT file:
- Load img_color_corrected
- Convert to LAB and classify pixels
- Build a multi-band classification_image of shape H x W x (N+1)
  Bands 0..N-1: class probabilities for user classes
  Band N: Unclassified mask (1 where max class probability < threshold, else 0)
- Write classification_image back into the same MAT file

Notes:
- Outside ROI (if roiData.lightnessValues exists) is set to NaN in all bands.
- Model must be generated by trainInteractivePixelClassifier.py.
"""

from __future__ import annotations

import glob
import os
import pickle
from typing import Dict, List

import cv2
import matplotlib.pyplot as plt
from matplotlib.colors import BoundaryNorm, ListedColormap
from matplotlib.patches import Patch
import numpy as np
from scipy.io import loadmat, savemat


def _safe_loadmat(path: str) -> Dict:
    try:
        return loadmat(path, simplify_cells=True)
    except TypeError:
        return loadmat(path, squeeze_me=True, struct_as_record=False)


def _to_dict(obj):
    if isinstance(obj, dict):
        return {k: _to_dict(v) for k, v in obj.items()}

    if hasattr(obj, "_fieldnames"):
        out = {}
        for name in obj._fieldnames:
            out[name] = _to_dict(getattr(obj, name))
        return out

    return obj


def load_model(model_path: str):
    with open(model_path, "rb") as f:
        model_data = pickle.load(f)

    if "classifier" not in model_data:
        raise ValueError(f"Missing 'classifier' in model file: {model_path}")
    if "class_names" not in model_data:
        raise ValueError(f"Missing 'class_names' in model file: {model_path}")

    clf = model_data["classifier"]
    class_names = list(model_data["class_names"])
    threshold = float(model_data.get("unclassified_threshold", 0.75))

    return clf, class_names, threshold


def get_roi_mask(mat_data: Dict, h: int, w: int) -> np.ndarray:
    roi_mask = np.ones((h, w), dtype=bool)

    roi_data = mat_data.get("roiData", None)
    if isinstance(roi_data, dict):
        lightness_values = roi_data.get("lightnessValues", None)
        if lightness_values is not None:
            arr = np.asarray(lightness_values)
            if arr.shape == (h, w):
                roi_mask = ~np.isnan(arr)

    return roi_mask


def save_prediction_plot(
    img_rgb: np.ndarray,
    roi_mask: np.ndarray,
    pred_map: np.ndarray,
    class_names: List[str],
    out_base: str,
):
    n = len(class_names)
    n_colors_needed = n + 1

    colors = np.array(
        [
            [0.0, 0.8, 0.0],
            [0.0, 0.2, 1.0],
            [1.0, 0.3, 0.0],
            [0.8, 0.0, 0.8],
            [0.2, 0.8, 0.8],
            [0.8, 0.8, 0.2],
            [0.6, 0.6, 0.6],
        ],
        dtype=np.float32,
    )
    if n_colors_needed > len(colors):
        extra = np.random.RandomState(0).rand(n_colors_needed - len(colors), 3).astype(np.float32)
        colors = np.vstack([colors, extra])

    pred_map_roi = np.ma.masked_where(~roi_mask, pred_map)
    cmap = ListedColormap(colors[:n_colors_needed])
    cmap.set_bad(alpha=0.0)
    norm = BoundaryNorm(np.arange(-0.5, n_colors_needed + 0.5, 1), n_colors_needed)

    input_rgb_vis = img_rgb.copy()
    non_roi = ~roi_mask
    if np.any(non_roi):
        gray_rgb = np.array([70, 70, 70], dtype=np.float32) / 255.0
        input_rgb_vis[non_roi] = 0.5 * input_rgb_vis[non_roi] + 0.5 * gray_rgb

    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.imshow(input_rgb_vis)
    plt.axis("off")
    plt.title("Input sRGB (ROI shown)")

    plt.subplot(1, 2, 2)
    plt.imshow(input_rgb_vis)
    plt.imshow(pred_map_roi, cmap=cmap, norm=norm, alpha=0.65)
    plt.axis("off")
    plt.title("Predicted Classes on sRGB (Unclassified is gray)")

    legend_names = class_names + ["Unclassified"]
    legend_handles = [
        Patch(facecolor=colors[i], edgecolor="black", label=legend_names[i])
        for i in range(n_colors_needed)
    ]
    plt.figlegend(
        handles=legend_handles,
        loc="lower center",
        ncol=min(4, n_colors_needed),
        frameon=False,
        fontsize=8,
    )
    plt.tight_layout()
    plt.savefig(out_base + ".png", dpi=150, transparent=True)
    plt.savefig(out_base + ".pdf")
    plt.close()


def classify_mat_file(
    mat_path: str,
    out_mat_path: str,
    clf,
    class_names: List[str],
    threshold: float,
):
    raw = _safe_loadmat(mat_path)
    data = _to_dict(raw)

    if "img_color_corrected" not in data:
        raise ValueError("Missing img_color_corrected")

    img_rgb = np.asarray(data["img_color_corrected"], dtype=np.float32)
    if img_rgb.ndim != 3 or img_rgb.shape[2] != 3:
        raise ValueError("img_color_corrected must be HxWx3")

    img_min = float(np.nanmin(img_rgb))
    img_max = float(np.nanmax(img_rgb))
    if img_max > 1.0 or img_min < 0.0:
        denom = img_max - img_min
        if denom > 0:
            img_rgb = (img_rgb - img_min) / denom
        else:
            img_rgb = np.zeros_like(img_rgb)

    img_rgb = np.clip(img_rgb, 0.0, 1.0)
    h, w, _ = img_rgb.shape

    img_bgr_u8 = cv2.cvtColor((img_rgb * 255).astype(np.uint8), cv2.COLOR_RGB2BGR)
    img_lab = cv2.cvtColor(img_bgr_u8, cv2.COLOR_BGR2LAB).astype(np.float32)

    X = img_lab.reshape(-1, 3)

    # Predict class probabilities and align to requested class order.
    prob_raw = clf.predict_proba(X)
    model_classes = np.asarray(clf.classes_)

    n = len(class_names)
    probs = np.zeros((X.shape[0], n), dtype=np.float32)
    for i, cls_name in enumerate(class_names):
        cls_idx = i
        matches = np.where(model_classes == cls_idx)[0]
        if matches.size > 0:
            probs[:, i] = prob_raw[:, matches[0]].astype(np.float32)

    max_prob = np.max(probs, axis=1)
    unclassified_band = (max_prob < threshold).astype(np.float32)
    pred_idx = np.argmax(probs, axis=1).astype(np.int32)
    pred_idx[max_prob < threshold] = n

    classification_image = np.concatenate(
        [probs, unclassified_band[:, None]], axis=1
    ).reshape(h, w, n + 1)
    pred_map = pred_idx.reshape(h, w)

    roi_mask = get_roi_mask(data, h, w)
    if roi_mask.shape == (h, w):
        classification_image[~roi_mask, :] = np.nan

    # Keep only savable data keys, then append output variables.
    save_data = {k: v for k, v in data.items() if not k.startswith("__")}
    save_data["classification_image"] = classification_image
    save_data["classification_band_names"] = np.array(class_names + ["Unclassified"], dtype=object)

    os.makedirs(os.path.dirname(out_mat_path), exist_ok=True)
    savemat(out_mat_path, save_data, do_compression=True)

    out_base = os.path.splitext(out_mat_path)[0] + "_classification"
    save_prediction_plot(img_rgb, roi_mask, pred_map, class_names, out_base)


def main():
    default_model = r"C:\Users\au686295\GitHub\data\AU\BeaImageColor2025\sites\calibrated_output\rf_training_output\vegetation_classifier_rf.pkl"
    model_path = input(f"Model path [{default_model}]: ").strip() or default_model

    default_mat_folder = r"C:\Users\au686295\GitHub\data\AU\BeaImageColor2025\sites\calibrated_output"
    mat_folder = input(f"MAT folder [{default_mat_folder}]: ").strip() or default_mat_folder

    default_output_folder = os.path.join(mat_folder, "classification_output")
    output_folder = input(f"Output folder for new MAT + plots [{default_output_folder}]: ").strip() or default_output_folder
    os.makedirs(output_folder, exist_ok=True)

    mat_files = sorted(glob.glob(os.path.join(mat_folder, "*_roi_data.mat")))
    if len(mat_files) == 0:
        mat_files = sorted(glob.glob(os.path.join(mat_folder, "*.mat")))

    if len(mat_files) == 0:
        raise FileNotFoundError(f"No MAT files found in: {mat_folder}")

    clf, class_names, threshold = load_model(model_path)
    # override threshold if user wants to specify a different value

    user_threshold = input(f"Enter threshold [{threshold:.3f}]: ").strip()
    if user_threshold:
        threshold = float(user_threshold)

    print(f"Found {len(mat_files)} MAT files.")
    print(f"Using threshold: {threshold:.3f}")
    print(f"Classes: {class_names} + ['Unclassified']")

    n_ok = 0
    n_skip = 0

    for i, mat_path in enumerate(mat_files, start=1):
        print(f"[{i}/{len(mat_files)}] {os.path.basename(mat_path)}")
        try:
            out_mat_path = os.path.join(output_folder, os.path.basename(mat_path))
            classify_mat_file(
                mat_path=mat_path,
                out_mat_path=out_mat_path,
                clf=clf,
                class_names=class_names,
                threshold=threshold,
            )
            n_ok += 1
        except Exception as exc:
            print(f"  Skipped: {exc}")
            n_skip += 1

    print("\nDone.")
    print(f"Saved MAT files: {n_ok}")
    print(f"Skipped files: {n_skip}")
    print(f"Output folder: {output_folder}")
    print("Appended variable name: classification_image")
    print("Also saved for each file: *_classification.png and *_classification.pdf")


if __name__ == "__main__":
    main()
